%(
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:css<simple-extras.css>,
	:custom-raku<extra-blocks.raku>,
	:license<Artistic-2.0>,
	:name<simple-extras>,
	:render,
	:template-raku<extra-templates.raku>,
	:version<0.2.0>,
)