%(
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:custom-raku(),
	:license<Artistic-2.0>,
	:name<rakudoc-table>,
	:render,
	:css<css/rakudoc-table-light.css>,
	:template-raku<rakudoc-table-templates.raku>,
	:version<0.1.2>,
)