%(
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:custom-raku<graphv-blocks.raku>,
	:license<Artistic-2.0>,
	:name<graphviz>,
	:render,
	:template-raku<graphv-templates.raku>,
	:version<0.2.0>,
)