%(
	:add-css<font-awesome.min.css>,
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:custom-raku(),
	:license<Artistic-2.0>,
	:name<font-awesome>,
	:assets('fonts',),
	:template-raku<fa-template.raku>,
	:version<0.1.0>,
)